stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/wasabi_report:latest" -t "$CI_REGISTRY/wasabi_report:master-$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY/wasabi_report:latest"
    - docker push "$CI_REGISTRY/wasabi_report:master-$CI_COMMIT_SHORT_SHA"
  only:
    - master
